---
name: Run tests
on:
  pull_request:
jobs:
  test:
    name: Build & Test
    uses: ./.github/workflows/build-and-test.workflow.yml

  validate-docker:
    name: Validate Docker Build
    uses: ./.github/workflows/docker.workflow.yml
    secrets: inherit
    with:
      push: false
